<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_schedule</name>
   <tag></tag>
   <elementGuidId>19b4318a-266a-47be-b796-202033a8c57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bookApptButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bookApptButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ed99995-393f-4fe7-bb24-f3e998457851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-colorPrimary cooler-reder-button css-1e6y48t-MuiButtonBase-root-MuiButton-root</value>
      <webElementGuid>ba72c5e0-bef2-4ae1-8862-ae1b2f989ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e885f39-1986-4cb7-8739-c52871b03a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookApptButton</value>
      <webElementGuid>3285fc05-6605-49d0-815b-22e2c62a7da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bookAppt</value>
      <webElementGuid>c22b1bee-447d-4839-877e-9f339f16a763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>schedule </value>
      <webElementGuid>758746b0-9106-4ebd-8063-118817f66025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[1]/div[1]/div[@class=&quot;homepage p-3&quot;]/div[@class=&quot;px-5 mx-5&quot;]/div[@class=&quot;d-flex justify-evenly mt-5&quot;]/div[1]/a[@id=&quot;bookApptButton&quot;]</value>
      <webElementGuid>8ef232cd-5b70-48b2-bae2-d614b7c52763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bookApptButton']</value>
      <webElementGuid>4d276d28-e574-4080-ac81-8d8588572185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div[5]/div/a</value>
      <webElementGuid>5c285af9-ca52-45c2-a06a-b63f3ddae8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'schedule')]</value>
      <webElementGuid>eaa3f4b1-36d5-41b2-b113-09af1c9987d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Appointment'])[1]/following::a[1]</value>
      <webElementGuid>9b28ff3c-be79-4bb2-b653-4f4f153ce92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Car Status'])[1]/preceding::a[1]</value>
      <webElementGuid>f04b7e31-1946-4dc4-bb01-430149ff707f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[1]</value>
      <webElementGuid>eba75e27-9152-40a6-bc54-6e9f7b051e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='schedule']/parent::*</value>
      <webElementGuid>b8070646-a77f-4299-ae81-073bc31bbc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bookAppt')]</value>
      <webElementGuid>da49c9e9-c17d-424b-b22b-511ffc61fb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>a15d014f-e589-41d6-a565-c38990eff6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bookApptButton' and @href = '/bookAppt' and (text() = 'schedule ' or . = 'schedule ')]</value>
      <webElementGuid>9a6c6982-ebed-432f-bfff-ff536fab2ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
