<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max_maxYear-number</name>
   <tag></tag>
   <elementGuidId>4fd46782-181e-475d-b984-d4b5d750bd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxYear-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxYear-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b154a1c-a044-43d4-8d91-7a09e8dc0ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>854a090c-a4aa-4570-a508-0be329ddd41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxYear-number</value>
      <webElementGuid>92e54563-95bc-45b6-afd0-d350351e959f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>775f45b6-92c8-4181-b80a-5fd1f2c5d935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1n4twyu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>69198ab1-f3f6-4d60-b4c7-11c7afee7ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxYear-number&quot;)</value>
      <webElementGuid>90da0fc1-b0bf-42fc-8a25-29d2ab337eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxYear-number']</value>
      <webElementGuid>6d10a8c0-5e65-488d-aa0c-290b8752cb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/ul/li/ul/li[2]/div[2]/div/input</value>
      <webElementGuid>8b9685d7-fe81-4948-90b6-a8e3e33afbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c6339856-336a-44f3-b766-d1a5219e546b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxYear-number' and @type = 'number']</value>
      <webElementGuid>3a1a5019-f97c-4f1f-8729-56b0ed726a51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
