<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Price_editedPrice (1)</name>
   <tag></tag>
   <elementGuidId>f1739ef6-8892-4e73-827f-da917964de5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editedPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editedPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04a766ac-a838-4825-be7b-27ae719ec2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editedPrice</value>
      <webElementGuid>f95e603c-a10a-452d-a852-2616d1173bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>663a41ef-fc8a-4a6a-9ff4-59313aba551b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>99.99</value>
      <webElementGuid>31d21882-6da7-421b-a699-ee94c3edb822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editedPrice&quot;)</value>
      <webElementGuid>ae5d2850-7de7-447b-901b-3352555dcdf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editedPrice']</value>
      <webElementGuid>652517a1-74c0-4c74-8c15-32249cad522f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>a5a15adc-6324-401c-8633-e0fdeb0f9234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>70042c4b-c9de-4c44-bccc-94efc29d6f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'editedPrice' and @type = 'text']</value>
      <webElementGuid>014931bc-b118-407c-925e-0b6fc0491627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
