<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service Price_editedPrice</name>
   <tag></tag>
   <elementGuidId>46e69855-a3f0-4ed1-9226-9e78746c11cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editedPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editedPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>040f5da8-692a-481f-b0e8-e07f77e4de54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editedPrice</value>
      <webElementGuid>c53a02de-1279-4089-99d4-bdc440136ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>451f1f53-a755-4533-8e8f-50455da5bdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>99.99</value>
      <webElementGuid>1e8200bf-b8c4-435c-aab8-ba3f7b255f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editedPrice&quot;)</value>
      <webElementGuid>c46ad3ea-ac08-4f25-908b-d09ed826af8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editedPrice']</value>
      <webElementGuid>f770739f-c938-4eb6-bb54-8f25ad60150e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>2983d423-4245-40d9-a9b2-1db74c39049e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>0ea75226-3873-4d52-9068-59dff4c0f95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'editedPrice' and @type = 'text']</value>
      <webElementGuid>0f1e119b-9d62-4580-997b-37659379198c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
