<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Min_minYear-number</name>
   <tag></tag>
   <elementGuidId>c7debfaf-540e-440b-965c-65a4c7285000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#minYear-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='minYear-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01e69cd7-07b1-4c93-91c2-b21e26f81f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72527d39-bd87-4ca6-bcaf-366f7be211c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minYear-number</value>
      <webElementGuid>def74b4e-8064-4678-8f6d-4baf4bd5932b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>488a4088-7dbf-47e6-a2b2-6075ebf4b814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1n4twyu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>e7ebe201-97b0-4835-8146-25fb4424e881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minYear-number&quot;)</value>
      <webElementGuid>c31f1286-f17f-40d2-b932-ec0a34d4fcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='minYear-number']</value>
      <webElementGuid>47a01ebb-dc33-4194-b5c2-3f33a46873e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div/div/div[2]/ul/li/ul/li[2]/div/div/input</value>
      <webElementGuid>5125307e-e82e-4c27-a37c-164df269a9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/input</value>
      <webElementGuid>e6dc4f2e-0ceb-4409-8bd1-66eded5508bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'minYear-number' and @type = 'number']</value>
      <webElementGuid>23bdc748-dded-4e2c-877b-c83d85c72d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
