<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mileage_mileage</name>
   <tag></tag>
   <elementGuidId>df9134f4-8994-4588-a6be-fc7085d5cad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mileage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mileage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>103ffa89-9e4b-4602-afe5-46ec66939a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>34435a18-5990-435d-903b-613c883ce6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mileage</value>
      <webElementGuid>35ecb641-72cc-4a76-a147-ca6561125585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mileage</value>
      <webElementGuid>41be9a42-320a-4397-a4b7-dc0f51ef7990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41b0d94f-287c-485b-ac13-8d874963d508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mileage&quot;)</value>
      <webElementGuid>275f05a0-9f35-4f48-ae0e-1d05a98b4aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mileage']</value>
      <webElementGuid>e045887b-e595-400c-8366-4d3df4d7a649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[7]/input</value>
      <webElementGuid>459fedb2-08d3-45ea-9ca3-7bafbc732370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>64fc84bb-c3ef-44da-b4dc-c37a651f2d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'mileage' and @name = 'mileage']</value>
      <webElementGuid>aef74d1a-338d-4400-8a93-4460cc5a16fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
