<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Signature_customer-signature</name>
   <tag></tag>
   <elementGuidId>76f46fa6-8574-4d7d-bbc2-9fbd72343e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-signature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-signature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b98a86f-1bc5-49bb-a2a0-9295d5d9710e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5dd76a02-d522-4253-9b02-957986f8a891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>customer-signature</value>
      <webElementGuid>ce6cc269-bef6-4e97-adac-82c884764fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-signature</value>
      <webElementGuid>07e38757-90f4-4f47-bc94-dfdb2cae288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sign Here: Alice Smith</value>
      <webElementGuid>451967a4-a5e1-4837-8825-69d44230c58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1efe9534-f9a4-4335-9417-a8d52e4d53d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>f98cfa38-d304-4c18-a23b-35b11cd87aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-signature&quot;)</value>
      <webElementGuid>bd70f253-19c1-4f42-88f5-9b5254a3ec78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-signature']</value>
      <webElementGuid>2fb2ee68-8291-4272-93dd-e988dbd0e232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>91a7ba1b-1ee6-4a15-87c6-11efa5c59e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ac1b488d-7bb1-492b-abd0-8036a19854c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customer-signature' and @placeholder = 'Sign Here: Alice Smith' and @type = 'text']</value>
      <webElementGuid>b17556e7-346d-4874-ab65-74cd24233faf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
