<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vin_VIN_carID</name>
   <tag></tag>
   <elementGuidId>3e0b20f1-1171-42ac-a4b2-59d414caa16f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VIN_carID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VIN_carID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9033e1fe-daa8-4935-9fd2-979bb41c9f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3154b6b3-840e-43ed-b65f-34ea1be607ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VIN_carID</value>
      <webElementGuid>21a1a117-ed46-4cdb-b33e-977b8a5b861d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VIN_carID</value>
      <webElementGuid>0d86aaaa-9920-42eb-a8f1-4435821a6835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06224439-4160-49b5-8e05-a714f53ad6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VIN_carID&quot;)</value>
      <webElementGuid>180e9364-f057-4145-900e-e806419e4e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VIN_carID']</value>
      <webElementGuid>9af0b182-e607-4318-ad06-ae5eca37fc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div/input</value>
      <webElementGuid>1973a950-af58-417a-8d97-d751ae071755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>33b60f4c-a98a-4d28-a373-2342983c6f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'VIN_carID' and @name = 'VIN_carID']</value>
      <webElementGuid>52d714b9-a539-44ab-bed2-e8cf62e935bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
