<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SSN_SSN</name>
   <tag></tag>
   <elementGuidId>7793c932-4719-4ecc-8d00-01ebdfd3b5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SSN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SSN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fd13b43-4a3f-4e28-862b-2c270cf4f8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6afc787-f6c7-4540-a305-9a5ccc474c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>a998a20b-77e5-4bc1-8d17-20e60036783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>263de295-5ffc-4099-b1ed-6699c4afa6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>651489f1-1ca3-4405-91c4-f6ade1d96890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SSN&quot;)</value>
      <webElementGuid>531d24c1-1f36-4d5b-8526-391353e8f7aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SSN']</value>
      <webElementGuid>5df6a74e-3e15-409e-978c-65dd36d20e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[12]/input</value>
      <webElementGuid>a71a5ff8-cba8-46ca-9d7e-36a13e01ffea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>f7cbea57-c563-476b-bd79-d4a39dc831da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SSN' and @name = 'SSN']</value>
      <webElementGuid>6d8fdafb-1411-4797-8982-fe9c5ce2b00c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
