<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Routing number_routing-number</name>
   <tag></tag>
   <elementGuidId>415a0d9a-f906-4ee8-bf07-c574ab3c382a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#routing-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='routing-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>719ec6cc-54d6-4bd4-9d20-758a7b652026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>586a0a3b-06e7-4668-840f-94c2f9f8289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>routing-number</value>
      <webElementGuid>b3767aca-7325-45a9-b9a7-50b65d43c108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>routing-number</value>
      <webElementGuid>324f660f-95ad-4a75-a6d9-bce80b5f94ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>c75ed8cf-f772-4933-ac36-efa05b3347f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5c805cd-016d-4289-9250-a6e61e733ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>8964143a-d3fe-4185-ad8c-ff086c0017bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input</value>
      <webElementGuid>025bcad6-800a-4132-b2a9-8fa750a6b6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routing-number&quot;)</value>
      <webElementGuid>813ab7dc-72dd-4de3-a86b-ca7769236c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='routing-number']</value>
      <webElementGuid>5baac2ff-8e85-4479-8750-ba1826b879d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/div[3]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>2db5de98-d3a9-4e37-b19e-1269d95d0845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b82d2b22-9f73-41a1-a6eb-8fbd6cf8cfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'routing-number' and @placeholder = '123456789' and @type = 'text']</value>
      <webElementGuid>89050c67-3e5a-4ab0-b6e7-e2a0b57cd9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
