<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Drivers License ID</name>
   <tag></tag>
   <elementGuidId>ad4872ce-7d2e-4d4c-ae7b-bcf4c6d80968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#driverID-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='driverID-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8695ac7a-1bbf-4340-a9c0-36d45c82f6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary Mui-focused Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined css-1jy569b-MuiFormLabel-root-MuiInputLabel-root</value>
      <webElementGuid>37ce9093-4407-4cfe-9c28-30b7777ba404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shrink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>83f6f1ab-b225-4276-a1b5-061602d30935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>driverID</value>
      <webElementGuid>20fc60cc-4be2-429a-b5bd-d6fce082b42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>driverID-label</value>
      <webElementGuid>27decebf-b4ed-4c47-92d1-6f7f9bb7278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Driver's License ID *</value>
      <webElementGuid>0644c2f1-f3ab-4553-b416-df0de6135cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;driverID-label&quot;)</value>
      <webElementGuid>cb377e73-8630-40f4-b37d-3094423be37c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='driverID-label']</value>
      <webElementGuid>7046f410-9663-45d8-9553-1ec9dae298cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/form/div/div[5]/div/label</value>
      <webElementGuid>eab1977b-e264-4d4f-a279-92a387a29ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>fb264e2d-5bf3-488c-a38b-6efe4ea85f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'driverID-label' and (text() = concat(&quot;Driver&quot; , &quot;'&quot; , &quot;s License ID *&quot;) or . = concat(&quot;Driver&quot; , &quot;'&quot; , &quot;s License ID *&quot;))]</value>
      <webElementGuid>22170897-0ea7-4cd9-86e4-eaff102567c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
