<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Last Name</name>
   <tag></tag>
   <elementGuidId>c4a23583-883f-43cc-bda3-e036d3118699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#last_name-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='last_name-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>97fd234f-a9ff-4d0a-a7ac-f515f2ca716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary Mui-focused Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined css-1jy569b-MuiFormLabel-root-MuiInputLabel-root</value>
      <webElementGuid>be5b7941-f16c-4fcc-a5f3-64b483c7091b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shrink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>998c2ac5-11c2-41ae-829c-f04577b9b4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>888809c8-14ec-4866-a7cf-f12f90af9dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>last_name-label</value>
      <webElementGuid>3556e6eb-4783-439e-926c-5efea28255bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name *</value>
      <webElementGuid>da9c2e12-b1f8-410e-90b3-9508a91ccca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;last_name-label&quot;)</value>
      <webElementGuid>3ad45376-91b5-44e4-bd9b-00ea97e17f5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='last_name-label']</value>
      <webElementGuid>44187444-dac9-4cd0-baa7-968d64e67411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/main/div/form/div/div[2]/div/label</value>
      <webElementGuid>7f9b4dff-7e75-40a6-ac47-82f7e2246832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last Name']/parent::*</value>
      <webElementGuid>18cc7d9d-49eb-4289-a1d2-1d9efb338dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>f90f361c-0c5d-4c3a-a0df-09e5d713ac03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'last_name-label' and (text() = 'Last Name *' or . = 'Last Name *')]</value>
      <webElementGuid>024023ea-2adf-4d20-8b79-4d74eac05cb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
