// constants.js

//DO NOT CHANGE THESE
export const BASE_URL = process.env.REACT_APP_BASE_URL;
export const FINANCE_URL = process.env.REACT_APP_FINANCE_URL;
//GO TO YOUR .env FILE TO CHANGE FROM PRODUCTION TO LOCAL URLS
